import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ✅ Load dataset
file_path = r"C:\Users\hp\Desktop\Intern_projects\Coffee_Sales_Analysis\Coffee_Sales_Analysis\data\index.csv"
df = pd.read_csv(file_path)

# ✅ Check available columns
print("Columns in dataset:", df.columns)

# ✅ Calculate total revenue per coffee type
revenue_per_coffee = df.groupby("coffee_name")["money"].sum().sort_values(ascending=False)

# ✅ Plot the revenue by product
plt.figure(figsize=(10, 5))
sns.barplot(x=revenue_per_coffee.index, y=revenue_per_coffee.values, palette="mako")
plt.xlabel("Coffee Name")
plt.ylabel("Total Revenue")
plt.title("Revenue Generated by Each Coffee Type")
plt.xticks(rotation=45)
plt.show()
